### ISSUE TITLE
How do we run v3 locally?

### ISSUE THREAD

**Issue by gituser123456789000** [BillFSmith/TilingZoeDepth#5]
How do we run v3 in locally?

**Comment by gituser123456789000** [comment]
**tried many things.. but tried + Code in the top right to add a box where I could type code

Among other things.. ran pip install google-colab.. it runs, green check mark, but error:**
Collecting google-colab
  Using cached google-colab-1.0.0.tar.gz (72 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting google-auth~=1.4.0 (from google-colab)
  Using cached google_auth-1.4.2-py2.py3-none-any.whl (64 kB)
Collecting ipykernel~=4.6.0 (from google-colab)
  Using cached ipykernel-4.6.1-py3-none-any.whl (104 kB)
Collecting ipython~=5.5.0 (from google-colab)
  Using cached ipython-5.5.0-py3-none-any.whl (758 kB)
Collecting notebook~=5.2.0 (from google-colab)
  Using cached notebook-5.2.2-py2.py3-none-any.whl (8.0 MB)
Collecting six~=1.12.0 (from google-colab)
  Using cached six-1.12.0-py2.py3-none-any.whl (10 kB)
Collecting pandas~=0.24.0 (from google-colab)
  Using cached pandas-0.24.2.tar.gz (11.8 MB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
Note: you may need to restart the kernel to use updated packages.

  error: subprocess-exited-with-error
  
  python setup.py egg_info did not run successfully.
  exit code: 1
  
  [15 lines of output]
  C:\Users\USERNAME\AppData\Local\Temp\pip-install-m5mw1s8l\pandas_953c923ee7d74e6cab83d243d567e57e\setup.py:12: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
    import pkg_resources
  C:\Users\USERNAME\anaconda3\Lib\site-packages\setuptools\__init__.py:84: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
  !!
  
          ********************************************************************************
          Requirements should be satisfied by a PEP 517 installer.
          If you are using pip, you can try `pip install --use-pep517`.
          ********************************************************************************
  
  !!
    dist.fetch_build_eggs(dist.setup_requires)
  error in pandas setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Expected end or semicolon (after version specifier)
      pytz >= 2011k
           ~~~~~~~^
  [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

Encountered error while generating package metadata.

See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.


**It say "Requirements should be satisfied by a PEP 517 installer.
          If you are using pip, you can try `pip install --use-pep517`"
OK.. should be satisfied.. Great, let's try it.

Run pip install --use-pep517 google-colab
Nope. Error:**

Collecting google-colab
  Using cached google-colab-1.0.0.tar.gz (72 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting google-auth~=1.4.0 (from google-colab)
  Using cached google_auth-1.4.2-py2.py3-none-any.whl (64 kB)
Collecting ipykernel~=4.6.0 (from google-colab)
  Using cached ipykernel-4.6.1-py3-none-any.whl (104 kB)
Collecting ipython~=5.5.0 (from google-colab)
  Using cached ipython-5.5.0-py3-none-any.whl (758 kB)
Collecting notebook~=5.2.0 (from google-colab)
  Using cached notebook-5.2.2-py2.py3-none-any.whl (8.0 MB)
Collecting six~=1.12.0 (from google-colab)
  Using cached six-1.12.0-py2.py3-none-any.whl (10 kB)
Collecting pandas~=0.24.0 (from google-colab)
  Using cached pandas-0.24.2.tar.gz (11.8 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Installing backend dependencies: started
  Installing backend dependencies: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'error'
Note: you may need to restart the kernel to use updated packages.

  error: subprocess-exited-with-error
  
  Preparing metadata (pyproject.toml) did not run successfully.
  exit code: 1
  
  [4 lines of output]
  <string>:12: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  error in pandas setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Expected end or semicolon (after version specifier)
      pytz >= 2011k
           ~~~~~~~^
  [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

Encountered error while generating package metadata.

See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Now what?**

**Comment by gituser123456789000** [comment]
It says Preparing metadata (pyproject.toml) did not run successfully.. so I ran pip install --use-pep517 pyproject.toml
Result: had most already and pyproject.toml Successfully installed:

Collecting pyproject.toml
  Downloading pyproject_toml-0.0.10-py3-none-any.whl (6.9 kB)
Requirement already satisfied: setuptools>=42 in c:\users\USERNAME\anaconda3\lib\site-packages (from pyproject.toml) (68.0.0)
Requirement already satisfied: wheel in c:\users\USERNAME\anaconda3\lib\site-packages (from pyproject.toml) (0.38.4)
Requirement already satisfied: toml in c:\users\USERNAME\anaconda3\lib\site-packages (from pyproject.toml) (0.10.2)
Requirement already satisfied: jsonschema in c:\users\USERNAME\anaconda3\lib\site-packages (from pyproject.toml) (4.17.3)
Requirement already satisfied: attrs>=17.4.0 in c:\users\USERNAME\anaconda3\lib\site-packages (from jsonschema->pyproject.toml) (22.1.0)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in c:\users\USERNAME\anaconda3\lib\site-packages (from jsonschema->pyproject.toml) (0.18.0)
Installing collected packages: pyproject.toml
Successfully installed pyproject.toml-0.0.10
Note: you may need to restart the kernel to use updated packages.

**Did it help? Can I now set up google-colab locally? Nope.
Ran pip install --use-pep517 google-colab
Error:**

Collecting google-colab
  Using cached google-colab-1.0.0.tar.gz (72 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting google-auth~=1.4.0 (from google-colab)
  Using cached google_auth-1.4.2-py2.py3-none-any.whl (64 kB)
Collecting ipykernel~=4.6.0 (from google-colab)
  Using cached ipykernel-4.6.1-py3-none-any.whl (104 kB)
Collecting ipython~=5.5.0 (from google-colab)
  Using cached ipython-5.5.0-py3-none-any.whl (758 kB)
Collecting notebook~=5.2.0 (from google-colab)
  Using cached notebook-5.2.2-py2.py3-none-any.whl (8.0 MB)
Collecting six~=1.12.0 (from google-colab)
  Using cached six-1.12.0-py2.py3-none-any.whl (10 kB)
Collecting pandas~=0.24.0 (from google-colab)
  Using cached pandas-0.24.2.tar.gz (11.8 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [4 lines of output]
      <string>:12: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
      error in pandas setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Expected end or semicolon (after version specifier)
          pytz >= 2011k
               ~~~~~~~^
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Now what?**

**Comment by gituser123456789000** [comment]
Ayyyy boys and girls... now we're finally getting somewhere... maybe

Yet another Google search finally turned up this:
https://stackoverflow.com/questions/77110771/error-when-pip-install-google-colab-use-pep517

Same problem:


i got this error:

Collecting pandas~=0.24.0 (from google-colab) Using cached pandas-0.24.2.tar.gz (11.8 MB) Installing build dependencies ... done Getting requirements to build wheel ... done Installing backend dependencies ... done Preparing metadata (pyproject.toml) ... error error: subprocess-exited-with-error

× Preparing metadata (pyproject.toml) did not run successfully. │ exit code: 1 ╰─> [4 lines of output] :12: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html error in pandas setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Expected end or semicolon (after version specifier) pytz >= 2011k ~~~~~~~^ [end of output]

note: This error originates from a subprocess, and is likely not a problem with pip. error: metadata-generation-failed

× Encountered error while generating package metadata. ╰─> See above for output.

note: This is an issue with the package mentioned above, not pip. hint: See above for details.


And the answer:
"Seems like PyPI hosts some old version. See also https://github.com/googlecolab/colabtools/issues/2598

I used the following command to install directly from source:

  pip install -e git+https://github.com/googlecolab/colabtools#egg=google.colab

Be warned that google.colab requires quite old package versions on its dependencies even when installed from source. So using virtualenv is recommended here."


OK.. nice.. finally got a direct link. Maybe that's obvious for coders, buit not for normal people. "But be warned" Oh dang.. Better heed the warning and figure that out first, before trying to install google.colab. So we should use virtualenv. OK. Found this on YouTube:
Python Tutorial: virtualenv and why you should use virtual environments
https://www.youtube.com/watch?v=N5vscPTWKOk

so I ran cd C:\Users\INSERTYOURUSERNAMEHERE\anaconda3\envs
[this moves you to that folder.. for the laymans]

then I ran virtualenv google-colab
[this creates a virtual environment folder.. seperate environment, so the warning from our answer "requires quite old package versions on its dependencies".. old dependencies and such.. doesn't interfere with other conda or python or whatever stuff that require newer versions]

then I ran conda activate google-colab
[to make that your active environment]

then I ran pip install -e git+https://github.com/googlecolab/colabtools#egg=google.colab
[to try again, for the manyith time...... And a whole bunch of stuff downloaded that didn't download on the other dozens of attempts]

So now we have google colab installed locally? I don't know.. seems like it. Let's go back to the v3 colab and try connecting locally again and see what happens...

**Comment by gituser123456789000** [comment]
So we're back in v3 colab.. and we're Connected (Local)... and we run press Ctrl + F9 to run... and we get the same error as when we started. Yippie.

---------------------------------------------------------------------------

ModuleNotFoundError                       Traceback (most recent call last)

Cell In[1], line 3
      1 #@title Code (press Ctrl + F9 to run)
----> 3 from google.colab import files
      4 get_ipython().run_line_magic('cd', "'/content/'")
      5 uploaded = files.upload()

ModuleNotFoundError: No module named 'google'


Now what? I don't know. Let's look at the error.. let's show code and look at the v3 code.. what's it telling me?
"from google.colab import files
%cd '/content/'"

Do I need google colab in a content folder? I don't know. Ouuu.. or do I put my content in a folder named content? Hmmm.. I don't know.

"ModuleNotFoundError: No module named 'google'"

Omg. Why? I have google colab installed. Took me hours. It's in env folder. I can find it.. why can't you find it?

I renamed the folder in envs to google.colab instead of google-colab, because the code has a . instead of a -
Did that help? No.

It says "from google.colab import files".. "No module named 'google'".. so it's looking for google.colab folder? But it can't find it? So the folder is in the wrong place? I don't know. Where's it supposed to be? I don't know.

How did I get the original v1 working... Hmmm...

What if I change the code to first go to the envs folder.. Haha.. I'm a dam genious..

So I add a line between the 1st and 2nd lines of code (actually the 3rd line I suppose, because the 2nd line is blank).. but I don't add a line.. I put my code right in that 2nd line, because if I add a line, the dam thing's probably going to say the rest of the code is out of line. And we can't have that... so the v3 code now starts this way:

#@title Code (press Ctrl + F9 to run)
%cd C:\Users\PUTYOURUSERNAMEHERE\anaconda3\envs
from google.colab import files

I used a % in front of the cd, because I look at the code here and the other cd references have the % in front of it, so that must mean it's important.. so that's what we use. Let's try this... Ouuuhuuhuu .. I figured it all out. You can't stop me...

Ok. So that did nothing. We get a slightly different error code:

C:\Users\YOURUSERNAME\anaconda3\envs

---------------------------------------------------------------------------

ModuleNotFoundError                       Traceback (most recent call last)

Cell In[6], line 3
      1 #@title Code (press Ctrl + F9 to run)
      2 get_ipython().run_line_magic('cd', 'C:\\Users\\YOURUSERNAME\\anaconda3\\envs')
----> 3 from google.colab import files
      4 get_ipython().run_line_magic('cd', "'/content/'")
      5 uploaded = files.upload()

ModuleNotFoundError: No module named 'google'

I told it exactly where to look to find google colab and it still couldn't find the dang thing.

OK.. check the code.. it seems we may need to surround it with 'these' 'apostrophes'... and we may need these forward slashes / / / to mark the folder instead of these backslashes \ \ \.. So we try some different variations... 

Surround our folder in our custom 2nd line with these ' '... and change our \ to /...

No good. New error.. or additional error:

[WinError 123] The filename, directory name, or volume label syntax is incorrect: "'C:/Users/YOURUSERNAME/anaconda3/envs/google.colab'"
C:\Users\YOURUSERNAME\anaconda3\envs

---------------------------------------------------------------------------

ModuleNotFoundError                       Traceback (most recent call last)

Cell In[9], line 3
      1 #@title Code (press Ctrl + F9 to run)
      2 get_ipython().run_line_magic('cd', "'C:/Users/YOURUSERNAME/anaconda3/envs/google.colab'")
----> 3 from google.colab import files
      4 get_ipython().run_line_magic('cd', "'/content/'")
      5 uploaded = files.upload()

ModuleNotFoundError: No module named 'google'


You may notice I also tried adding google.colab folder in another attempt, just in case.. 

Hmmm..

**Comment by gituser123456789000** [comment]
OK... so when I got v1 working.. I see /content/ is looking for Google Drive content. 

You had to mount your Google Drive using code:
from google.colab import drive
drive.mount('/content/drive')

To then select an image, you had to use code:
img = Image.open('/content/drive/yourdrivename/foldername/a.jpg')

If you wanted to open a local file, you used code:
img = Image.open('C:/Users/YOURUSERNAME//Downloads/etcwhateveryourfoldernameis/a.jpg')

So I think I may need to change /content/ to where my files are? I don't know. I need sleep.. and that doesn't solve the "ModuleNotFoundError: No module named 'google'" problem. /content/ just seems like it would be the next problem if I figured out the ModuleNotFoundError: No module named 'google' problem

**Comment by cmore86** [comment]
I have this running locally. I just recreated the same environment locally as on colab and changed the parts of the code posted to local instead of colab. I am running a rtx 4090 local...way faster than colab...and I don't get kicked off

**Comment by gituser123456789000** [comment]
> I have this running locally. I just recreated the same environment locally as on colab and changed the parts of the code posted to local instead of colab. I am running a rtx 4090 local...way faster than colab...and I don't get kicked off

I have no clue how to do that. If you want to take the time and write out step by step how to do it, that would be cool, but it's up to you. I was able to get version 1 running 'locally' using the colab and 'connect to local runtime'. This version was giving errors when I tried that way.. saying it couldn't find google.colab or something, even though I was right there on google colab but running a local runtime. I don't understand these things, but can likely follow steps easily.

Either way, Depth-Anything looks to be the new hotness at the moment in depth map making, so now it would probably be good to get a TilingDepth-Anything

**Comment by cmore86** [comment]
Connecting to local runtime is not the same as running local. You are using your code but their hardware.
I am no coder but here is what I did. I looked at his script and saw what running.  Colab is running on unbutu. I got WSL 2 for windows to run linux.  I then went to the main repository of zoedepth and they have instructions on how to set up a local environment. ( environment.yml) Set up zoedepth in the environment. Then brought his script into notepad++.....ha and that is where the fun began. Chat GTP will become your friend. Both of my local scripts are posted here in pull requests so after you set up zoedepth and the environment all you have do is run the script in whatever directory you have zoedepth.

I have tried messing with changes a lot. If you look at his code the tiles 4,4 and 8,8 from what I understand those are pixel sizes the depth model looks at. By increasing those numbers I found better detail being held. The other thing was I changed out the 16bitpng to a 32bit tiff ( I have a 3d modelling background). I also tried 32bit exr. So the best detail I get is at 8,8 & 12,12 (runs in multiples of 32) with 32 bit tiff. With tiff at 32 there NO stepping. I have to convert the 32bit in Photoshop because zbrush won't take a 32bit import.  My main purpose was 2.5d bas relief stuff as I do a lot of cnc carving. Do I see this replacing hand modeling anytime soon? Nope but it sure is fun to mess with.
![examples](https://github.com/BillFSmith/TilingZoeDepth/assets/153390755/9aa70e0c-a0ba-4c81-b80a-e5acbcef5391)

**Comment by jones873** [comment]
cmore86, would you be kind enouth to test my version of your original picture  in blender please, i`m currently testing thease in Vectric aspire it would be very interresting to see what the results are, it`s a 16bit png, many thanks

![Untiled](https://github.com/BillFSmith/TilingZoeDepth/assets/136728071/0e0068e2-7798-46e0-a341-0ca8b6911b06)

**Comment by cmore86** [comment]
Here you go. On the surface it looks like more detail but it is causing indents in places there should be none and some really sharp lines ie spikes, like around the lips and details on the circular head piece details.

What methods are you using? It almost looks like your combining the original
![indian test](https://github.com/BillFSmith/TilingZoeDepth/assets/153390755/ab66c138-622f-46d4-82cc-d97b1cae7752)
 image with the depth map

**Comment by jones873** [comment]
Thanks for doing the test, it seems there was a issue in how I enlarged the original image..
Anyway I have produced a smaller one, seems to have resolved the spikes and anything else can be modeled out...

![Untitled](https://github.com/BillFSmith/TilingZoeDepth/assets/136728071/8041754e-f9ad-44b4-bae2-a8742caad097)

**Comment by gituser123456789000** [comment]
Closing the issue...
the GUI fork worked for me to get it running locally.
